name: publish-docs

on:
  push:
    branches:
    - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: checkout master
      uses: actions/checkout@v2
    - name: build docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "./docs"
    - name: checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
    - name: Commit documentation changes
      run: |
          cp -r docs/_build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update do